### ISSUE TITLE
Users can delete the products in the saved lists

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/beauty-List#5]
## 📐 Functionality

Users will be able to delete any saved listings that are within the saved items page.

## 🖼️ Wireframes

Mobile:
https://www.figma.com/file/FygER9DI2JeIFNgEiG4cJQ/Christina-Le---Ajax-Project?node-id=1%3A3

Desktop:
https://www.figma.com/file/FygER9DI2JeIFNgEiG4cJQ/Christina-Le---Ajax-Project?node-id=1%3A4

![Screen Shot 2022-03-11 at 12 14 30 AM](https://user-images.githubusercontent.com/97194651/157828690-884ef4ae-6a67-4019-9e69-2b950493e85c.png)

![Screen Shot 2022-03-11 at 12 14 42 AM](https://user-images.githubusercontent.com/97194651/157828709-6aca28a6-21c2-4b77-8a88-79affe924288.png)
![Screen Shot 2022-03-11 at 12 14 48 AM](https://user-images.githubusercontent.com/97194651/157828715-43114292-2dae-4897-8ff5-84575b77cbe4.png)
![Screen Shot 2022-03-11 at 12 14 54 AM](https://user-images.githubusercontent.com/97194651/157828718-c54bdd17-a089-4a23-8896-8732d6a9ed09.png)

## ✅ Task List

- [x] Add a delete button to each listing in the saved items page
- [x] Add an event listener for the delete button
- [x] Ensure that if the user clicks yes, the listing will get deleted from the page and the DOM tree
- [x] Clean up any styling
- [x] Test in private browsing mode
- [x] Fix all errors
